before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/stac/
    binary: stac
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - image_templates:
      - "ghcr.io/planetlabs/go-stac:{{ .Tag }}"
      - "ghcr.io/planetlabs/go-stac:v{{ .Major }}"
    build_flag_templates:
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.url=https://github.com/planetlabs/{{ .ProjectName }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github-native
