name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          args: "--out-${NO_FUTURE}format colored-line-number"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: '1.18'
      - run: go test -v ./...
