name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.21'
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54.1
          args: "--out-${NO_FUTURE}format colored-line-number"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.21'
      - run: go test -v ./...
