name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24'
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24'
      - run: go test -v ./...
